// Bundles the engine into a single string the app can inline into the snippet
// people copy out. The result is committed, so `pnpm build` needs no pre-step —
// and a test recomputes the hash below and fails if the sources have moved on.
//
//   pnpm build:engine
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");
const GLOBAL = "Carousel3D";
const OUT = path.join(ROOT, "src", "engine", "dist", "engineSource.ts");

/**
 * esbuild minifies code, not the contents of strings — and the stylesheet is a
 * string. It is written to be read in src/engine/styles.ts, with comments
 * explaining which four rules are load-bearing, and none of that has any
 * business riding along in a block somebody pastes into their page. Comments go,
 * runs of whitespace collapse to one space. Nothing that changes what it means.
 */
const minifyCssStrings = {
  name: "minify-css-strings",
  setup(builder) {
    builder.onLoad({ filter: /engine[\\/]styles\.ts$/ }, async (args) => {
      const source = await readFile(args.path, "utf8");
      const contents = source.replace(/`([^`]*)`/gs, (whole, body) => {
        if (!body.includes("{") || body.includes("${")) return whole;
        const squeezed = body
          .replace(/\/\*[\s\S]*?\*\//g, "")
          .replace(/\s+/g, " ")
          .trim();
        return `\`${squeezed}\``;
      });
      return { contents, loader: "ts" };
    });
  },
};

const result = await build({
  plugins: [minifyCssStrings],
  entryPoints: [path.join(ROOT, "src", "engine", "embed.ts")],
  bundle: true,
  minify: true,
  format: "iife",
  globalName: GLOBAL,
  target: "es2019",
  legalComments: "none",
  // esbuild's iife wrapper declares the global with a plain top-level `var`,
  // which becomes a global inside a <script> tag but *not* inside a strict-mode
  // eval — where it lands in the eval's own scope and the page sees nothing.
  // Saying it outright costs sixty bytes and works in both.
  footer: { js: `if(typeof globalThis<"u")globalThis.${GLOBAL}=${GLOBAL};` },
  write: false,
  metafile: true,
});

const source = result.outputFiles[0].text.trim();

// Exactly what esbuild pulled in, so the hash covers the real dependency set
// rather than a hand-kept list that drifts. Adding an import changes the file
// that imports it, so a new dependency invalidates the hash too.
const inputs = Object.keys(result.metafile.inputs)
  .map((file) => path.relative(ROOT, path.resolve(ROOT, file)))
  .sort();

const hash = createHash("sha256");
for (const input of inputs) {
  hash.update(input);
  hash.update(await readFile(path.join(ROOT, input)));
}

const file = `// GENERATED by scripts/build-engine.mjs — do not edit.
//
// The engine, bundled and minified, as a string. This is what gets inlined into
// the block people copy out, and it is the *same code the preview runs* — which
// is the whole architecture in one file: what you see is what you copy, by
// construction rather than by discipline.
//
// Committed on purpose, so a production build has no pre-step. engineSource.test.ts
// recomputes the hash from the sources below and fails if they have moved on.
// Run \`pnpm build:engine\` when they have.

/** The global the bundle defines. */
export const ENGINE_GLOBAL = ${JSON.stringify(GLOBAL)};

/** Sources the bundle was built from, as esbuild resolved them. */
export const ENGINE_INPUTS = ${JSON.stringify(inputs, null, 2)};

/** sha256 over those sources, in this order, name then contents. */
export const ENGINE_HASH = ${JSON.stringify(`sha256:${hash.digest("hex")}`)};

export const ENGINE_SOURCE = ${JSON.stringify(source)};
`;

await writeFile(OUT, file);

const bytes = Buffer.byteLength(source, "utf8");
process.stdout.write(
  `${path.relative(ROOT, OUT)} — ${(bytes / 1024).toFixed(1)}KB minified from ${inputs.length} files\n`,
);
