// Turns the source stills in images/ into the webp the carousel actually loads.
//
// Square is the prepared shape on purpose: each preset's cardAspect crops
// further from the centre at render time, so one prepared file serves every
// style and nothing needs re-exporting when a style changes.
//
// The source PNGs are gitignored and never copied into public/ — only the
// generated webp ships. Run with `pnpm prep:images`.

import { readdir, readFile, writeFile, mkdir, rm } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCE_DIR = path.join(ROOT, "images");
const OUT_DIR = path.join(ROOT, "public", "img");
const DATA_FILE = path.join(ROOT, "src", "data", "images.ts");
const ALT_FILE = path.join(ROOT, "src", "data", "image-alt.json");

const LARGE = 1200;
const SMALL = 600;
const QUALITY = 82;
const PLACEHOLDER = 12;

/** dannystuart_abstract_blob_shape_…_6fb60c67-…_0.png → 05-abstract-blob-shape */
function slugify(filename, index) {
  const withoutExtension = filename.replace(/\.[a-z0-9]+$/i, "");
  const words = withoutExtension
    .replace(/^dannystuart_/, "")
    // Order matters: uuids first, or the flag strip below swallows their leading
    // block and leaves the rest looking like words.
    .replace(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/gi, " ")
    // A job reference, not a description — and only as far as its id, or this
    // eats the prompt that follows it.
    .replace(/https?s*[:.]?\/{0,2}[a-z0-9._-]*mj\.run[a-z0-9-]*/gi, " ")
    // Midjourney flags: --chaos_5, --ar_11, --stylize_250, --sref_…
    .replace(/--[a-z0-9._]+/gi, " ")
    .replace(/\(\d+\)/g, " ")
    .replace(/[^a-z0-9]+/gi, " ")
    .trim()
    .split(/\s+/)
    .filter(
      (word) =>
        word.length > 1 &&
        !/^\d+$/.test(word) &&
        // Leftover fragments of an id: hex-only and carrying a digit.
        !(/^[0-9a-f]{4,}$/i.test(word) && /\d/.test(word)),
    );

  let slug = "";
  for (const word of words) {
    const next = slug ? `${slug}-${word.toLowerCase()}` : word.toLowerCase();
    if (next.length > 44) break;
    slug = next;
  }
  const number = String(index + 1).padStart(2, "0");
  return `${number}-${slug || "untitled"}`;
}

async function readAltText() {
  try {
    return JSON.parse(await readFile(ALT_FILE, "utf8"));
  } catch {
    return {};
  }
}

async function main() {
  const files = (await readdir(SOURCE_DIR))
    .filter((name) => /\.(png|jpe?g|webp)$/i.test(name))
    .sort((a, b) => a.localeCompare(b, "en"));

  if (files.length === 0) throw new Error(`no images found in ${SOURCE_DIR}`);

  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  // Alt text is hand-written by looking at each picture and lives in its own
  // file, so regenerating the webp can never wipe it.
  const existingAlt = await readAltText();
  const altBySlug = {};
  const entries = [];

  for (const [index, file] of files.entries()) {
    const slug = slugify(file, index);
    const source = sharp(path.join(SOURCE_DIR, file), { failOn: "error" });
    const { width, height } = await source.metadata();

    const square = () =>
      sharp(path.join(SOURCE_DIR, file)).resize(LARGE, LARGE, { fit: "cover", position: "centre" });

    await square().webp({ quality: QUALITY }).toFile(path.join(OUT_DIR, `${slug}.webp`));
    await sharp(path.join(SOURCE_DIR, file))
      .resize(SMALL, SMALL, { fit: "cover", position: "centre" })
      .webp({ quality: QUALITY })
      .toFile(path.join(OUT_DIR, `${slug}@0.5x.webp`));

    const placeholder = await sharp(path.join(SOURCE_DIR, file))
      .resize(PLACEHOLDER, PLACEHOLDER, { fit: "cover", position: "centre" })
      .blur(1.4)
      .webp({ quality: 32 })
      .toBuffer();

    altBySlug[slug] = existingAlt[slug] ?? "";
    entries.push({
      slug,
      src: `/img/${slug}.webp`,
      srcSmall: `/img/${slug}@0.5x.webp`,
      blurData: `data:image/webp;base64,${placeholder.toString("base64")}`,
      width: LARGE,
      height: LARGE,
      source: { file, width, height },
    });

    process.stdout.write(`  ${slug}  (from ${width}×${height})\n`);
  }

  await mkdir(path.dirname(ALT_FILE), { recursive: true });
  await writeFile(ALT_FILE, `${JSON.stringify(altBySlug, null, 2)}\n`, "utf8");

  const written = entries
    .map(
      (entry) => `  {
    slug: ${JSON.stringify(entry.slug)},
    src: ${JSON.stringify(entry.src)},
    srcSmall: ${JSON.stringify(entry.srcSmall)},
    blurData: ${JSON.stringify(entry.blurData)},
    width: ${entry.width},
    height: ${entry.height},
    alt: ${JSON.stringify(altBySlug[entry.slug])},
  },`,
    )
    .join("\n");

  const contents = `// Generated by scripts/prep-images.mjs — do not edit by hand.
// Run \`pnpm prep:images\` after changing anything in images/.
//
// Prepared square at ${LARGE}px with a ${SMALL}px half-size, quality ${QUALITY},
// centre-cropped. Each preset's cardAspect crops further from the centre at
// render time, so one file serves every style.

export interface PreparedImage {
  slug: string;
  src: string;
  srcSmall: string;
  /** A ${PLACEHOLDER}px blurred webp, inline, to fill the card before the real file lands. */
  blurData: string;
  width: number;
  height: number;
  /**
   * Written by looking at the picture — never inferred from the filename.
   * Edit src/data/image-alt.json, then re-run \`pnpm prep:images\`.
   */
  alt: string;
}

export const IMAGES: PreparedImage[] = [
${written}
];
`;

  await mkdir(path.dirname(DATA_FILE), { recursive: true });
  await writeFile(DATA_FILE, contents, "utf8");

  const missing = entries.filter((entry) => !altBySlug[entry.slug]).length;
  process.stdout.write(`\n${entries.length} images prepared into public/img/\n`);
  if (missing > 0) {
    process.stdout.write(`${missing} still need alt text — write it in src/data/image-alt.json\n`);
  }
}

await main();
